# Generated by Django 5.2.4 on 2025-08-28 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_register_email_alter_register_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('Bus', 'Bus'), ('Flight', 'Flight'), ('Train', 'Train')], max_length=20)),
                ('from_station', models.CharField(max_length=100)),
                ('to_station', models.CharField(max_length=100)),
                ('journey_date', models.DateField()),
                ('seats', models.PositiveIntegerField(default=1)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Confirmed', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.register')),
            ],
        ),
    ]
